export const INDUSTRIES = [
  'Energy & Chemicals',
  'Precision Engineering',
  'Marine & Offshore',
  'Aerospace',
  'Electronics',
  'Construction',
  'Real Estate',
  'Cleaning',
  'Security',
  'Logistics',
  'Air Transport',
  'Sea Transport',
  'Land Transport',
  'Wholesale Trade',
  'Healthcare',
  'Education',
  'Professional Services',
  'ICT and Media',
  'Financial Services',
  'Food Services',
  'Retail',
  'Hotels',
  'Food Manufacturing'
];
